### ISSUE TITLE
Migrate Landing Section

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-infra-issues#86]
## Descriptions: 
Migrate Landing Section to Astro along with all subsections:

### Tasks:

- [ ] Section and subsections added to site.
- [ ] MD content updated as necessary to  fit the **MDX** and **Zod** schemes for the site.
- [ ] View Transitions to provide animated transitions from one frame to another

### Sign off by stake holders:
- [ ] Documentation 
- [ ] Design
- [ ] Development (CSS, React, or Infra)

### Resources:
* [Landing Page](https://www.patternfly.org/)
* [MDX](https://mdxjs.com/)
* [Zod documentation schema](https://zod.dev/) 
* [JSX support and React support](https://docs.astro.build/en/guides/integrations-guide/react/#installation)

**Comment by dlabaj** [comment]
No major updates needed to support this.
