### ISSUE TITLE
Migrate A11y section to Astro

### ISSUE THREAD

**Issue by dlabaj** [patternfly/patternfly-infra-issues#91]
## Descriptions: 
Migrate A11y section [Astro](https://astro.build/) along with all subsections.

### Tasks:
- [ ] [About A11y](https://www.patternfly.org/accessibility/about-accessibility) added to site
- [ ] [A11y scorecard](https://www.patternfly.org/accessibility/accessibility-scorecard) added to site
- [ ] [Design for A11y](https://www.patternfly.org/accessibility/design-for-accessibility) added to site
- [ ] [Develop for A11y](https://www.patternfly.org/accessibility/develop-for-accessibility) added to site
- [ ] [PatternFly A11y](https://www.patternfly.org/accessibility/patternflys-accessibility) added to site
- [ ] [Testing for A11y](https://www.patternfly.org/accessibility/testing-your-accessibility) added to site

### Definition of done:
* Each section should be updated to conform to fit the **MDX** and **Zod** schemes for the site. 
* Sections should have animation to feel like a single page app.
* Tested, builds, and passes linting.
* Signed off by the stake holders.

#### Sign off by stake holders:
- [ ] Documentation 
- [ ] Design
- [ ] Development (CSS, React, or Infra)

#### Resources:
* [Landing Page](https://www.patternfly.org/)
* [MDX](https://mdxjs.com/)
* [Zod documentation schema](https://zod.dev/) 
* [JSX support and React support](https://docs.astro.build/en/guides/integrations-guide/react/#installation)

**Comment by dlabaj** [comment]
No major updates needed to support this.
